### Exercise 1

In [40]:
#@Janina Hohnholz, FH Aachen Campus Jülich, FB3

import numpy as np     #import all the directories needed, avoid star/master imports
 
def multiply(A,B):     #defintion of the function 
    result=np.dot(A,B)
    print(result)

In [41]:
x=np.random.rand(3,3)  #creating first random array
#print(x)              #for validation only
y=np.random.rand(3,3)  #creating second random array
#print(y)              #for validation only

In [42]:
multiply(x,y)          #function calling

[[0.60933799 0.36122272 0.65378983]
 [0.94430786 0.7757858  0.80363276]
 [0.76386682 0.70075797 0.64848355]]
